version: '3.8'

services:
  first_microservice:
    build:
      context: ./gpt-creating # Update with the actual path to the first microservice
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://shecouldnthelpwithmymind:paA4gMHwvR9Lajmk@gpt-creating.3bvrx6v.mongodb.net/Project0?retryWrites=true&w=majority&appName=gpt-creating
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis

  second_microservice:
    build:
      context: ./video-rendering # Update with the actual path to the second microservice
    ports:
      - "5000:5000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

volumes:
  mongo-data:
